# Netlify configuration for SlideWindr
# This file should be at the repository root

[build]
  # Build from the presenta-react subdirectory
  base = "presenta-react"

  # Build command
  command = "npm run build"

  # Directory with build output (relative to base)
  publish = "dist"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[build.environment]
  NODE_VERSION = "20"
