# Netlify configuration for SlideWindr

[build]
  # Directory to run build command from
  base = "."

  # Build command
  command = "npm run build"

  # Directory with build output (Vite default)
  publish = "dist"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JS files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS files
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (optional - can also set in Netlify UI)
[build.environment]
  NODE_VERSION = "20"
